export const schemaStatements: string[] = [
  `CREATE TABLE IF NOT EXISTS tenants (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    created_at INTEGER NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    email TEXT,
    name TEXT,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
  );`,
  `CREATE TABLE IF NOT EXISTS auth_credentials (
    user_id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    password_salt TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS auth_oauth_accounts (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    provider_user_id TEXT NOT NULL,
    email TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    UNIQUE (provider, provider_user_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS auth_sessions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    last_seen_at INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
  );`,
  `CREATE TABLE IF NOT EXISTS auth_email_otps (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL,
    user_id TEXT,
    purpose TEXT NOT NULL DEFAULT 'sign_in',
    code_hash TEXT NOT NULL,
    expires_at INTEGER NOT NULL,
    consumed_at INTEGER,
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS security_events (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    session_id TEXT,
    event_type TEXT NOT NULL,
    description TEXT NOT NULL,
    ip_address TEXT,
    user_agent TEXT,
    metadata_json TEXT,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS memberships (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    role TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    UNIQUE (tenant_id, user_id),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS app_bootstrap_state (
    state_key TEXT PRIMARY KEY,
    state_value TEXT,
    updated_at INTEGER NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    company_id TEXT,
    name TEXT NOT NULL,
    description TEXT,
    workstream_key TEXT,
    is_default_workstream INTEGER NOT NULL DEFAULT 0,
    created_by TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS companies (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    canonical_project_id TEXT UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    issue_prefix TEXT,
    brand_color TEXT,
    created_by TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (canonical_project_id) REFERENCES projects(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS company_members (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    company_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    role TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    UNIQUE (company_id, user_id),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS company_workstreams (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    company_id TEXT NOT NULL,
    project_id TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    is_default INTEGER NOT NULL DEFAULT 0,
    created_by TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS company_goals (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    company_id TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    created_by TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS company_agents (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    company_id TEXT NOT NULL,
    user_id TEXT,
    role_key TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    wakeup_policy_json TEXT,
    runtime_policy_json TEXT,
    created_by TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS company_routines (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    company_id TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    wakeup_type TEXT NOT NULL DEFAULT 'automation',
    schedule_json TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    last_run_at INTEGER,
    created_by TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS company_approvals (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    company_id TEXT NOT NULL,
    source_type TEXT NOT NULL,
    source_id TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    title TEXT NOT NULL,
    summary TEXT,
    payload_json TEXT,
    requested_by TEXT NOT NULL,
    decided_by TEXT,
    decided_at INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (requested_by) REFERENCES users(id),
    FOREIGN KEY (decided_by) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS company_activity (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    company_id TEXT NOT NULL,
    project_id TEXT,
    category TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'info',
    message TEXT NOT NULL,
    metadata_json TEXT,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (project_id) REFERENCES projects(id)
  );`,
  `CREATE TABLE IF NOT EXISTS company_instruction_bundles (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    company_id TEXT NOT NULL,
    bundle_key TEXT NOT NULL,
    title TEXT NOT NULL,
    markdown TEXT NOT NULL,
    summary TEXT,
    created_by TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    UNIQUE (company_id, bundle_key),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS items (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    parent_id TEXT,
    kind TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    created_by TEXT NOT NULL,
    assignee_id TEXT,
    approver_id TEXT,
    issue_key TEXT,
    priority TEXT NOT NULL DEFAULT 'medium',
    goal_id TEXT,
    execution_mode TEXT NOT NULL,
    active_execution_session_id TEXT,
    last_execution_session_id TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (goal_id) REFERENCES company_goals(id)
  );`,
  `CREATE TABLE IF NOT EXISTS issue_comments (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    company_id TEXT,
    project_id TEXT NOT NULL,
    item_id TEXT NOT NULL,
    author_user_id TEXT,
    author_name TEXT,
    author_email TEXT,
    source_type TEXT NOT NULL DEFAULT 'human',
    body TEXT NOT NULL,
    metadata_json TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (item_id) REFERENCES items(id),
    FOREIGN KEY (author_user_id) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS issue_attachments (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    company_id TEXT,
    project_id TEXT NOT NULL,
    item_id TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'attachment',
    title TEXT NOT NULL,
    url TEXT,
    mime_type TEXT,
    metadata_json TEXT,
    created_by TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (item_id) REFERENCES items(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS issue_attachment_blobs (
    attachment_id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    file_name TEXT NOT NULL,
    size_bytes INTEGER NOT NULL,
    content_base64 TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (attachment_id) REFERENCES issue_attachments(id),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
  );`,
  `CREATE TABLE IF NOT EXISTS issue_documents (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    company_id TEXT,
    project_id TEXT NOT NULL,
    item_id TEXT NOT NULL,
    title TEXT NOT NULL,
    summary TEXT,
    body_markdown TEXT,
    metadata_json TEXT,
    created_by TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (item_id) REFERENCES items(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS issue_approvals (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    company_id TEXT,
    project_id TEXT NOT NULL,
    item_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    title TEXT NOT NULL,
    summary TEXT,
    payload_json TEXT,
    requested_by TEXT NOT NULL,
    decided_by TEXT,
    decided_at INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (item_id) REFERENCES items(id),
    FOREIGN KEY (requested_by) REFERENCES users(id),
    FOREIGN KEY (decided_by) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS agent_runs (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    requested_by TEXT NOT NULL,
    root_prompt TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (project_id) REFERENCES projects(id)
  );`,
  `CREATE TABLE IF NOT EXISTS agent_steps (
    id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    agent_name TEXT NOT NULL,
    step_order INTEGER NOT NULL,
    input_payload TEXT,
    output_payload TEXT,
    model TEXT,
    input_tokens INTEGER,
    output_tokens INTEGER,
    status TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (run_id) REFERENCES agent_runs(id)
  );`,
  `CREATE TABLE IF NOT EXISTS project_agents (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    owner_user_id TEXT NOT NULL,
    system_prompt TEXT NOT NULL,
    latest_run_id TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    UNIQUE (tenant_id, project_id)
  );`,
  `CREATE TABLE IF NOT EXISTS agent_messages (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    project_agent_id TEXT NOT NULL,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    model TEXT,
    input_tokens INTEGER,
    output_tokens INTEGER,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (project_agent_id) REFERENCES project_agents(id)
  );`,
  `CREATE TABLE IF NOT EXISTS project_search_index (
    tenant_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    content TEXT NOT NULL,
    item_count INTEGER NOT NULL DEFAULT 0,
    epic_count INTEGER NOT NULL DEFAULT 0,
    updated_at INTEGER NOT NULL,
    PRIMARY KEY (tenant_id, project_id),
    FOREIGN KEY (project_id) REFERENCES projects(id)
  );`,
  `CREATE TABLE IF NOT EXISTS app_memory_entries (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    project_id TEXT,
    source_app TEXT NOT NULL,
    source_type TEXT NOT NULL,
    source_key TEXT NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    summary TEXT,
    metadata_json TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    UNIQUE (tenant_id, source_app, source_type, source_key),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
  );`,
  `CREATE TABLE IF NOT EXISTS agent_action_events (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    project_agent_id TEXT,
    run_id TEXT,
    source_message_id TEXT,
    actions_json TEXT NOT NULL,
    event_type TEXT NOT NULL,
    created_by TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (project_id) REFERENCES projects(id)
  );`,
  `CREATE TABLE IF NOT EXISTS agent_action_logs (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    user_email TEXT,
    action_type TEXT NOT NULL,
    agent_name TEXT,
    project_id TEXT,
    project_name TEXT,
    status TEXT NOT NULL,
    error_message TEXT,
    tokens_used INTEGER NOT NULL DEFAULT 0,
    tokens_input INTEGER NOT NULL DEFAULT 0,
    tokens_output INTEGER NOT NULL DEFAULT 0,
    model_name TEXT,
    api_endpoint TEXT,
    api_provider TEXT,
    response_time_ms INTEGER,
    metadata TEXT,
    request_preview TEXT,
    response_preview TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  );`,
  `CREATE TABLE IF NOT EXISTS planning_contexts (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    project_id TEXT,
    created_by TEXT NOT NULL,
    plan_intent TEXT NOT NULL,
    selected_project_id TEXT,
    execution_mode TEXT NOT NULL,
    onboarding_answers_json TEXT NOT NULL,
    qualifying_answers_json TEXT NOT NULL,
    uploaded_document TEXT,
    markdown_bundle TEXT,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
  );`,
  `CREATE TABLE IF NOT EXISTS project_memory_docs (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    layer_key TEXT NOT NULL,
    title TEXT NOT NULL,
    markdown TEXT NOT NULL,
    summary TEXT,
    source_context_json TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    UNIQUE (tenant_id, project_id, layer_key),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
  );`,
  `CREATE TABLE IF NOT EXISTS proposals (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    source TEXT NOT NULL,
    title TEXT NOT NULL,
    summary TEXT,
    status TEXT NOT NULL,
    impact_level TEXT NOT NULL,
    actions_json TEXT NOT NULL,
    diff_json TEXT,
    requested_by TEXT NOT NULL,
    approved_by TEXT,
    approved_at INTEGER,
    rejected_by TEXT,
    rejected_at INTEGER,
    applied_by TEXT,
    applied_at INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
  );`,
  `CREATE TABLE IF NOT EXISTS service_connections (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    service_type TEXT NOT NULL,
    access_token TEXT,
    refresh_token TEXT,
    service_url TEXT,
    service_account_id TEXT,
    service_account_email TEXT,
    service_account_name TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, service_type, service_account_id)
  );`,
  `CREATE TABLE IF NOT EXISTS github_repos (
    id TEXT PRIMARY KEY,
    connection_id TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    github_repo_id INTEGER NOT NULL,
    owner TEXT NOT NULL,
    name TEXT NOT NULL,
    full_name TEXT NOT NULL,
    description TEXT,
    url TEXT,
    private INTEGER NOT NULL DEFAULT 0,
    stars INTEGER NOT NULL DEFAULT 0,
    forks INTEGER NOT NULL DEFAULT 0,
    open_issues INTEGER NOT NULL DEFAULT 0,
    synced_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, full_name)
  );`,
  `CREATE TABLE IF NOT EXISTS github_commits (
    id TEXT PRIMARY KEY,
    connection_id TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    repo_id TEXT NOT NULL,
    sha TEXT NOT NULL,
    message TEXT NOT NULL,
    author_name TEXT,
    author_email TEXT,
    author_github_id INTEGER,
    committed_at TEXT NOT NULL,
    additions INTEGER NOT NULL DEFAULT 0,
    deletions INTEGER NOT NULL DEFAULT 0,
    extracted_tasks TEXT,
    extracted_epics TEXT,
    mentioned_issues TEXT,
    UNIQUE (repo_id, sha)
  );`,
  `CREATE TABLE IF NOT EXISTS github_contributors (
    id TEXT PRIMARY KEY,
    connection_id TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    repo_id TEXT NOT NULL,
    github_user_id INTEGER,
    login TEXT NOT NULL,
    avatar_url TEXT,
    commits_count INTEGER NOT NULL DEFAULT 0,
    top_languages TEXT,
    top_directories TEXT,
    extracted_skills TEXT,
    last_commit_at TEXT,
    UNIQUE (repo_id, login)
  );`,
  `CREATE TABLE IF NOT EXISTS project_github_links (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    connection_id TEXT NOT NULL,
    repo_full_name TEXT NOT NULL,
    repo_owner TEXT NOT NULL,
    repo_name TEXT NOT NULL,
    collaboration_mode TEXT NOT NULL DEFAULT 'agent_build',
    review_on_push INTEGER NOT NULL DEFAULT 0,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    UNIQUE (tenant_id, project_id),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (connection_id) REFERENCES service_connections(id)
  );`,
  `CREATE TABLE IF NOT EXISTS project_repo_runs (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    created_by TEXT NOT NULL,
    connection_id TEXT NOT NULL,
    repo_full_name TEXT NOT NULL,
    branch_name TEXT NOT NULL,
    base_branch TEXT NOT NULL DEFAULT 'main',
    status TEXT NOT NULL DEFAULT 'queued',
    requested_files_json TEXT,
    build_commands_json TEXT,
    commit_message TEXT,
    pr_title TEXT,
    pr_body TEXT,
    external_run_id TEXT,
    logs_json TEXT,
    result_json TEXT,
    error_message TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    started_at INTEGER,
    completed_at INTEGER,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (connection_id) REFERENCES service_connections(id)
  );`,
  `CREATE TABLE IF NOT EXISTS jira_projects (
    id TEXT PRIMARY KEY,
    connection_id TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    jira_project_id TEXT NOT NULL,
    key TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    project_type TEXT,
    url TEXT,
    lead_account_id TEXT,
    lead_display_name TEXT,
    synced_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, key)
  );`,
  `CREATE TABLE IF NOT EXISTS jira_issues (
    id TEXT PRIMARY KEY,
    connection_id TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    jira_issue_id TEXT NOT NULL,
    key TEXT NOT NULL,
    issue_type TEXT,
    summary TEXT NOT NULL,
    description TEXT,
    status TEXT,
    status_category TEXT,
    priority TEXT,
    assignee_account_id TEXT,
    assignee_display_name TEXT,
    epic_key TEXT,
    epic_name TEXT,
    story_points REAL,
    time_estimate_seconds INTEGER,
    time_spent_seconds INTEGER,
    created_at TEXT,
    updated_at TEXT,
    due_date TEXT,
    resolved_at TEXT,
    extracted_requirements TEXT,
    extracted_acceptance_criteria TEXT,
    UNIQUE (project_id, key)
  );`,
  `CREATE TABLE IF NOT EXISTS admin_api_keys (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    name TEXT NOT NULL,
    secret TEXT NOT NULL,
    model TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_by TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS admin_agent_configs (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    name TEXT NOT NULL,
    prompt TEXT NOT NULL,
    model TEXT NOT NULL,
    provider TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1,
    updated_by TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    UNIQUE (tenant_id, name),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS admin_runtime_config (
    tenant_id TEXT PRIMARY KEY,
    primary_provider TEXT NOT NULL,
    primary_model TEXT NOT NULL,
    fallback_provider TEXT,
    fallback_model TEXT,
    updated_by TEXT NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS admin_integration_configs (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    integration_key TEXT NOT NULL,
    status TEXT NOT NULL,
    summary TEXT,
    config_json TEXT,
    updated_by TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    UNIQUE (tenant_id, integration_key),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS custom_connectors (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    connector_type TEXT NOT NULL,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL,
    access_scope TEXT NOT NULL DEFAULT 'personal',
    endpoint_url TEXT,
    command TEXT,
    transport TEXT,
    auth_mode TEXT NOT NULL DEFAULT 'none',
    header_name TEXT,
    auth_token TEXT,
    config_json TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    UNIQUE (tenant_id, connector_type, slug),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS ai_model_catalog (
    id TEXT PRIMARY KEY,
    provider TEXT NOT NULL,
    model_id TEXT NOT NULL,
    label TEXT NOT NULL,
    tier TEXT NOT NULL,
    category TEXT NOT NULL,
    is_free INTEGER NOT NULL DEFAULT 0,
    context_length INTEGER NOT NULL DEFAULT 0,
    supports_structured_output INTEGER NOT NULL DEFAULT 0,
    supports_vision INTEGER NOT NULL DEFAULT 0,
    quality_score REAL NOT NULL DEFAULT 0,
    sort_score REAL NOT NULL DEFAULT 0,
    source TEXT NOT NULL DEFAULT 'openrouter',
    metadata_json TEXT,
    last_seen_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    UNIQUE (provider, model_id)
  );`,
  `CREATE TABLE IF NOT EXISTS project_member_assignments (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    member_id TEXT NOT NULL,
    assigned_by TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    UNIQUE (tenant_id, project_id, member_id),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (project_id) REFERENCES projects(id)
  );`,
  `CREATE TABLE IF NOT EXISTS usage_events (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    feature_key TEXT NOT NULL,
    provider TEXT,
    model TEXT,
    request_count INTEGER NOT NULL DEFAULT 1,
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL,
    metadata_json TEXT,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
  );`,
  `CREATE TABLE IF NOT EXISTS billing_customers (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL UNIQUE,
    stripe_customer_id TEXT NOT NULL UNIQUE,
    email TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
  );`,
  `CREATE TABLE IF NOT EXISTS billing_subscriptions (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    stripe_customer_id TEXT,
    stripe_subscription_id TEXT NOT NULL UNIQUE,
    stripe_checkout_session_id TEXT,
    plan_key TEXT NOT NULL,
    status TEXT NOT NULL,
    current_period_end INTEGER,
    cancel_at_period_end INTEGER NOT NULL DEFAULT 0,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
  );`,
  `CREATE TABLE IF NOT EXISTS billing_credit_grants (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    source_type TEXT NOT NULL,
    source_ref TEXT,
    requests_granted INTEGER NOT NULL DEFAULT 0,
    tokens_granted INTEGER NOT NULL DEFAULT 0,
    amount_cents INTEGER,
    currency TEXT,
    note TEXT,
    created_by TEXT,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS app_runtime_events (
    id TEXT PRIMARY KEY,
    tenant_id TEXT,
    user_id TEXT,
    project_id TEXT,
    route_key TEXT NOT NULL,
    category TEXT NOT NULL,
    severity TEXT NOT NULL,
    message TEXT NOT NULL,
    metadata_json TEXT,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (project_id) REFERENCES projects(id)
  );`,
  `CREATE TABLE IF NOT EXISTS debug_sessions (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    created_by TEXT NOT NULL,
    mode TEXT NOT NULL,
    status TEXT NOT NULL,
    summary TEXT NOT NULL,
    evidence_sources_json TEXT,
    linked_proposal_id TEXT,
    linked_run_id TEXT,
    diagnosis TEXT,
    final_recommendation TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (linked_proposal_id) REFERENCES proposals(id),
    FOREIGN KEY (linked_run_id) REFERENCES agent_runs(id)
  );`,
  `CREATE TABLE IF NOT EXISTS debug_steps (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    step_order INTEGER NOT NULL,
    step_name TEXT NOT NULL,
    status TEXT NOT NULL,
    input_payload_json TEXT,
    output_payload_json TEXT,
    stdout TEXT,
    stderr TEXT,
    exit_code INTEGER,
    stack_trace TEXT,
    files_touched_json TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (session_id) REFERENCES debug_sessions(id),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
  );`,
  `CREATE TABLE IF NOT EXISTS debug_artifacts (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    artifact_type TEXT NOT NULL,
    title TEXT NOT NULL,
    content_json TEXT,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (session_id) REFERENCES debug_sessions(id),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
  );`,
  `CREATE TABLE IF NOT EXISTS repo_review_sessions (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    debug_session_id TEXT,
    repo_full_name TEXT NOT NULL,
    review_mode TEXT NOT NULL,
    summary TEXT,
    status TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (debug_session_id) REFERENCES debug_sessions(id)
  );`,
  `CREATE TABLE IF NOT EXISTS workspace_skills (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    description TEXT NOT NULL,
    instructions TEXT NOT NULL,
    status TEXT NOT NULL,
    source TEXT NOT NULL,
    pattern_key TEXT,
    usage_count INTEGER NOT NULL DEFAULT 0,
    created_by TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    UNIQUE (tenant_id, slug),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS skill_request_patterns (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    project_id TEXT,
    pattern_key TEXT NOT NULL,
    example_request TEXT NOT NULL,
    request_count INTEGER NOT NULL DEFAULT 1,
    suggested_skill_id TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    last_seen_at INTEGER NOT NULL,
    UNIQUE (tenant_id, pattern_key),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (suggested_skill_id) REFERENCES workspace_skills(id)
  );`,
  `CREATE TABLE IF NOT EXISTS assistant_threads (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    company_id TEXT,
    project_id TEXT,
    owner_user_id TEXT NOT NULL,
    title TEXT NOT NULL,
    visibility TEXT NOT NULL DEFAULT 'private',
    status TEXT NOT NULL DEFAULT 'idle',
    summary TEXT,
    current_page TEXT,
    current_route TEXT,
    active_goal TEXT,
    latest_message_id TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (owner_user_id) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS assistant_thread_members (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    thread_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'viewer',
    added_by TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    UNIQUE (thread_id, user_id),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (thread_id) REFERENCES assistant_threads(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS assistant_messages (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    thread_id TEXT NOT NULL,
    user_id TEXT,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    model TEXT,
    status TEXT NOT NULL DEFAULT 'completed',
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (thread_id) REFERENCES assistant_threads(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS assistant_message_parts (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    thread_id TEXT NOT NULL,
    message_id TEXT NOT NULL,
    part_order INTEGER NOT NULL,
    part_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'completed',
    summary TEXT,
    payload_json TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (thread_id) REFERENCES assistant_threads(id),
    FOREIGN KEY (message_id) REFERENCES assistant_messages(id)
  );`,
  `CREATE TABLE IF NOT EXISTS assistant_pending_actions (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    thread_id TEXT NOT NULL,
    company_id TEXT,
    project_id TEXT,
    kind TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    title TEXT NOT NULL,
    summary TEXT,
    payload_json TEXT NOT NULL,
    created_by TEXT NOT NULL,
    confirmed_by TEXT,
    cancelled_by TEXT,
    executed_at INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (thread_id) REFERENCES assistant_threads(id),
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS execution_sessions (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    company_id TEXT,
    project_id TEXT,
    thread_id TEXT,
    item_id TEXT,
    proposal_id TEXT,
    initiated_by TEXT NOT NULL,
    mode TEXT NOT NULL,
    provider TEXT NOT NULL,
    transport TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued',
    title TEXT NOT NULL,
    summary TEXT,
    target_ref TEXT,
    callback_secret TEXT,
    external_run_id TEXT,
    metadata_json TEXT,
    result_json TEXT,
    error_message TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    started_at INTEGER,
    completed_at INTEGER,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (thread_id) REFERENCES assistant_threads(id),
    FOREIGN KEY (item_id) REFERENCES items(id),
    FOREIGN KEY (proposal_id) REFERENCES proposals(id),
    FOREIGN KEY (initiated_by) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS execution_session_events (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    status TEXT,
    message TEXT,
    payload_json TEXT,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (session_id) REFERENCES execution_sessions(id)
  );`,
  `CREATE TABLE IF NOT EXISTS item_execution_links (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    item_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    link_type TEXT NOT NULL DEFAULT 'latest',
    created_at INTEGER NOT NULL,
    UNIQUE (item_id, session_id, link_type),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (item_id) REFERENCES items(id),
    FOREIGN KEY (session_id) REFERENCES execution_sessions(id)
  );`,
  `CREATE INDEX IF NOT EXISTS idx_projects_tenant ON projects(tenant_id);`,
  `CREATE INDEX IF NOT EXISTS idx_companies_tenant_updated ON companies(tenant_id, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_company_members_company_user ON company_members(company_id, user_id);`,
  `CREATE INDEX IF NOT EXISTS idx_company_workstreams_company_updated ON company_workstreams(company_id, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_company_goals_company_updated ON company_goals(company_id, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_company_agents_company_updated ON company_agents(company_id, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_company_routines_company_updated ON company_routines(company_id, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_company_approvals_company_updated ON company_approvals(company_id, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_company_activity_company_created ON company_activity(company_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_company_instruction_bundles_company_key ON company_instruction_bundles(company_id, bundle_key);`,
  `CREATE INDEX IF NOT EXISTS idx_auth_oauth_accounts_user ON auth_oauth_accounts(user_id, provider);`,
  `CREATE INDEX IF NOT EXISTS idx_auth_sessions_user_expires ON auth_sessions(user_id, expires_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_auth_email_otps_email_purpose ON auth_email_otps(email, purpose, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_security_events_user_created ON security_events(user_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_security_events_session_created ON security_events(session_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_memberships_tenant_user ON memberships(tenant_id, user_id);`,
  `CREATE INDEX IF NOT EXISTS idx_projects_tenant_updated ON projects(tenant_id, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_items_project_parent_sort ON items(project_id, parent_id, sort_order);`,
  `CREATE INDEX IF NOT EXISTS idx_items_tenant_project_updated ON items(tenant_id, project_id, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_items_tenant ON items(tenant_id);`,
  `CREATE INDEX IF NOT EXISTS idx_agent_runs_tenant_project ON agent_runs(tenant_id, project_id, updated_at);`,
  `CREATE INDEX IF NOT EXISTS idx_agent_steps_run_order ON agent_steps(run_id, step_order);`,
  `CREATE INDEX IF NOT EXISTS idx_project_agents_tenant_project ON project_agents(tenant_id, project_id);`,
  `CREATE INDEX IF NOT EXISTS idx_agent_messages_agent_created ON agent_messages(project_agent_id, created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_project_search_index_tenant_updated ON project_search_index(tenant_id, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_app_memory_entries_tenant_project_updated ON app_memory_entries(tenant_id, project_id, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_app_memory_entries_tenant_source_updated ON app_memory_entries(tenant_id, source_app, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_agent_action_events_tenant_project_created ON agent_action_events(tenant_id, project_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_agent_action_logs_tenant_created ON agent_action_logs(tenant_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_planning_contexts_tenant_created ON planning_contexts(tenant_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_project_memory_docs_tenant_project_updated ON project_memory_docs(tenant_id, project_id, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_project_memory_docs_tenant_layer_updated ON project_memory_docs(tenant_id, layer_key, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_proposals_tenant_project_created ON proposals(tenant_id, project_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_proposals_tenant_status ON proposals(tenant_id, status, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_admin_api_keys_tenant_active ON admin_api_keys(tenant_id, is_active, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_admin_agent_configs_tenant_sort ON admin_agent_configs(tenant_id, sort_order, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_admin_runtime_config_updated ON admin_runtime_config(updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_admin_integration_configs_tenant_status ON admin_integration_configs(tenant_id, status, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_custom_connectors_tenant_type_scope ON custom_connectors(tenant_id, connector_type, access_scope, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_custom_connectors_tenant_user ON custom_connectors(tenant_id, user_id, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_ai_model_catalog_provider_category ON ai_model_catalog(provider, category, is_free, sort_score DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_project_member_assignments_tenant_project ON project_member_assignments(tenant_id, project_id, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_project_github_links_tenant_project ON project_github_links(tenant_id, project_id, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_project_github_links_tenant_repo ON project_github_links(tenant_id, repo_full_name, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_project_repo_runs_project_created ON project_repo_runs(tenant_id, project_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_usage_events_tenant_created ON usage_events(tenant_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_usage_events_tenant_feature_created ON usage_events(tenant_id, feature_key, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_billing_subscriptions_tenant_status ON billing_subscriptions(tenant_id, status, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_billing_credit_grants_tenant_user_created ON billing_credit_grants(tenant_id, user_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_billing_credit_grants_source_ref ON billing_credit_grants(tenant_id, source_type, source_ref);`,
  `CREATE INDEX IF NOT EXISTS idx_app_runtime_events_tenant_created ON app_runtime_events(tenant_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_app_runtime_events_project_created ON app_runtime_events(tenant_id, project_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_app_runtime_events_severity_created ON app_runtime_events(severity, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_debug_sessions_tenant_project_updated ON debug_sessions(tenant_id, project_id, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_debug_sessions_tenant_status_updated ON debug_sessions(tenant_id, status, updated_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_debug_steps_session_order ON debug_steps(session_id, step_order, created_at ASC);`,
  `CREATE INDEX IF NOT EXISTS idx_debug_artifacts_session_created ON debug_artifacts(session_id, created_at ASC);`,
  `CREATE INDEX IF NOT EXISTS idx_repo_review_sessions_tenant_project_updated ON repo_review_sessions(tenant_id, project_id, updated_at DESC);`
  ,`CREATE INDEX IF NOT EXISTS idx_workspace_skills_tenant_status ON workspace_skills(tenant_id, status, updated_at DESC);`
  ,`CREATE INDEX IF NOT EXISTS idx_skill_request_patterns_tenant_seen ON skill_request_patterns(tenant_id, last_seen_at DESC);`
  ,`CREATE INDEX IF NOT EXISTS idx_assistant_threads_tenant_updated ON assistant_threads(tenant_id, updated_at DESC);`
  ,`CREATE INDEX IF NOT EXISTS idx_assistant_threads_project_updated ON assistant_threads(tenant_id, project_id, updated_at DESC);`
  ,`CREATE INDEX IF NOT EXISTS idx_assistant_threads_visibility_updated ON assistant_threads(tenant_id, visibility, updated_at DESC);`
  ,`CREATE INDEX IF NOT EXISTS idx_assistant_thread_members_thread_user ON assistant_thread_members(thread_id, user_id);`
  ,`CREATE INDEX IF NOT EXISTS idx_assistant_thread_members_user_thread ON assistant_thread_members(user_id, updated_at DESC);`
  ,`CREATE INDEX IF NOT EXISTS idx_assistant_messages_thread_created ON assistant_messages(thread_id, created_at ASC);`
  ,`CREATE INDEX IF NOT EXISTS idx_assistant_message_parts_message_order ON assistant_message_parts(message_id, part_order ASC);`
  ,`CREATE INDEX IF NOT EXISTS idx_assistant_pending_actions_thread_updated ON assistant_pending_actions(thread_id, updated_at DESC);`
  ,`CREATE INDEX IF NOT EXISTS idx_assistant_pending_actions_status_updated ON assistant_pending_actions(tenant_id, status, updated_at DESC);`
  ,`CREATE INDEX IF NOT EXISTS idx_execution_sessions_project_updated ON execution_sessions(tenant_id, project_id, updated_at DESC);`
  ,`CREATE INDEX IF NOT EXISTS idx_execution_sessions_thread_updated ON execution_sessions(tenant_id, thread_id, updated_at DESC);`
  ,`CREATE INDEX IF NOT EXISTS idx_execution_sessions_status_updated ON execution_sessions(tenant_id, status, updated_at DESC);`
  ,`CREATE INDEX IF NOT EXISTS idx_execution_session_events_session_created ON execution_session_events(session_id, created_at ASC);`
  ,`CREATE INDEX IF NOT EXISTS idx_item_execution_links_item_created ON item_execution_links(item_id, created_at DESC);`
  ,`CREATE TABLE IF NOT EXISTS project_memory_files (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    para_category TEXT NOT NULL DEFAULT 'resources',
    path TEXT NOT NULL,
    title TEXT NOT NULL,
    markdown TEXT NOT NULL DEFAULT '',
    summary TEXT,
    tags_json TEXT,
    created_by TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
  );`
  ,`CREATE INDEX IF NOT EXISTS idx_project_memory_files_project ON project_memory_files(tenant_id, project_id, updated_at DESC);`
  ,`CREATE TABLE IF NOT EXISTS workspace_plugins (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    slug TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    version TEXT NOT NULL DEFAULT '1.0.0',
    manifest_json TEXT NOT NULL DEFAULT '{}',
    worker_url TEXT,
    ui_url TEXT,
    status TEXT NOT NULL DEFAULT 'draft',
    created_by TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    UNIQUE(tenant_id, slug),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
  );`
  ,`CREATE TABLE IF NOT EXISTS workspace_plugin_grants (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    plugin_id TEXT NOT NULL,
    company_id TEXT,
    capabilities_json TEXT NOT NULL DEFAULT '[]',
    created_at INTEGER NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
  );`
]
